# Foundry Configuration File
# See more config options at: https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
optimizer = true
optimizer_runs = 200
libs = ['lib']
src = 'src'
test = 'test'
out = 'out'
fs_permissions = [{access = "write", path = "./reports"}]

[rpc_endpoints]
mainnet = "${RPC_MAINNET_URL}"
polygon = "${RPC_POLYGON_URL}"
